name: tic_tac_toe
description: Tic-Tac-Toe
version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^0.3.5
  flutter_mobx: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  mobx_codegen: ^0.3.3+1

flutter:
  uses-material-design: true